services:
  db:
    image: bitnami/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_DATABASE=manager
    ports:
      - 3306:3306
    volumes:
      - ./db:/bitnami/mysql/data